### ISSUE TITLE
[BUG] Can't start Magma 1.16 Server

### ISSUE THREAD

**Issue by PinguIsBedless** [magmafoundation/Magma-1.16.x#112]
**Describe the bug**
A clear and concise description of what the bug is: When I try to start the Server, I get this bug.

**To Reproduce**
1. Go to 'your server folder'
2. Click on 'run.bat(your bat file)'
3. Scroll down to 'the error'
4. [14:35:04] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.UnsupportedOperationException: Cannot redefine singleton Server
        at org.bukkit.Bukkit.setServer(Bukkit.java:85) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:286) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:149) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:19) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:236) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:767) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:281) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}
[14:35:04] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 667e3ab9-1a70-49b8-b8ea-1c8b312fb08e

**Expected behavior**
A clear and concise description of what you expected to happen:

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: No Mod
 - Mod Version: No Mod
 - Magma Version: magma-1.16.5-36.1.32-bfbc2c6-DEV-installer.jar 
 - OS: Windows 10

**Additional context**
Add any other context about the problem here:
This is the console output from start to crash:
[14:34:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.32-bfbc2c6-DEV, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[14:34:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_281 by Oracle Corporation
[14:34:24] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[14:34:24] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Jona/Downloads/magma%20server/Builds/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
[14:34:26] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[14:34:41] [modloading-worker-1/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 36.1.32-bfbc2c6-DEV, for MC 1.16.5 with MCP 20210115.111550
[14:34:41] [modloading-worker-1/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v36.1.32-bfbc2c6-DEV Initialized
[14:34:43] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[14:34:44] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: AHEAD Current: 36.1.32-bfbc2c6-DEV Target: null
[14:34:47] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:34:49] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, forge-1.16.5-36.1.32-bfbc2c6-DEV-universal.jar, bukkit
[14:34:51] [Worker-Main-6/INFO] [minecraft/RecipeManager]: Loaded 7 recipes
[14:34:55] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.16.5
[14:34:55] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
[14:34:56] [Server thread/INFO] [Minecraft/]: This server is running Magma version git-Magma-1.16.5-36.1.32-bfbc2c6-DEV (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[14:34:57] [Server thread/INFO] [Minecraft/]: Debug logging is enabled
[14:34:57] [Server thread/INFO] [Minecraft/]: Using 4 threads for Netty based IO
[14:34:57] [Server thread/INFO] [/]: Server Ping Player Sample Count: 12
[14:34:57] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
[14:34:57] [Server thread/INFO] [minecraft/MinecraftServer]: Generating keypair
[14:34:58] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:25565
[14:34:58] [Server thread/INFO] [minecraft/NetworkSystem]: Using default channel type
[14:35:04] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.UnsupportedOperationException: Cannot redefine singleton Server
        at org.bukkit.Bukkit.setServer(Bukkit.java:85) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:286) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:149) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:19) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:236) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:767) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:281) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}
[14:35:04] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 667e3ab9-1a70-49b8-b8ea-1c8b312fb08e

**Comment by UeberallGebannt** [comment]
Should be fixed in latest release
