### ISSUE TITLE
Essentials errors when executing commands (NoSuchMethodError)

### ISSUE THREAD

**Issue by Column01** [magmafoundation/Magma-1.16.x#134]
When running essentials commands, essentials throws a `NoSuchMethodError` on calls to `org.bukkit.World.getChunkAtAsync()`. This results in a failure to execute the command and a large blob in the console. 

[Here](https://gist.github.com/ab00afd49eea1957fa360586e3358fa5) is a log file showing this error

[Essentials release version](https://github.com/EssentialsX/Essentials/releases/tag/2.18.2)
Magma Version: `113bec6`

**Comment by Romaindu35** [comment]
This bug is create because PaperLib detect class 'com.destroystokyo.paper.PaperConfig', so essential active paper environment, but all paper patch is not implement. Here the patch paper-async is missing, so the method 'org.bukkit.World#getChunkAtAsync' is not add, but essential try to get this method, so 'NoSuchMehodError' is create.
To fix that you can:
1) Rename 'com.destroystokyo.paper.PaperConfig'
2) Move 'com.destroystokyo.paper.PaperConfig' in other package
3) use ASM to return false at method 'io.papermc.lib.PaperLib.isPaper'

**Comment by Column01** [comment]
That's a bandaid fix, paper should just fully be implemented to fix it

**Comment by MagnusHJensen** [comment]
> This bug is create because PaperLib detect class `com.destroystokyo.paper.PaperConfig`, so essential active paper environment, but all paper patch is not implement. Here the patch paper-async is missing, so the method `org.bukkit.World#getChunkAtAsync` is not add, but essential try to get this method, so `NoSuchMehodError` is create.
> To fix that you can:
> 
> 1. Rename `com.destroystokyo.paper.PaperConfig`
> 2. Move `com.destroystokyo.paper.PaperConfig` in other package
> 3. use ASM to return false at method `io.papermc.lib.PaperLib.isPaper`

This is a general issue, with more plugins. Build: e8445f4
WorldGuard for example doesn't work either, on some events, because of the paperlib issue.

Issue:
```log
[10:18:55] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to WorldGuard v7.0.5+3827266
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:484) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:451) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:172) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:1324) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:982) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:184) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:965) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:959) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:945) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:874) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getState(Z)Lorg/bukkit/block/BlockState;
        at com.sk89q.worldguard.bukkit.paperlib.features.blockstatesnapshot.BlockStateSnapshotOptionalSnapshots.getBlockState(BlockStateSnapshotOptionalSnapshots.java:8) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.paperlib.environments.Environment.getBlockState(Environment.java:100) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.paperlib.PaperLib.getBlockState(PaperLib.java:190) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.util.Blocks.getConnected(Blocks.java:49) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteract(EventAbstractionListener.java:503) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?] {re:classloading}
        ... 23 more
```
