### ISSUE TITLE
[Bug]: Server does not load mixins

### ISSUE THREAD

**Issue by wolflord212312** [magmafoundation/Magma-1.16.x#169]
### What happened?

On first start after install it fails to load the mixins and stops.

### Mods

Progressive Bosses (by Insane96MCP)
Event's Lootbags (by mceventhorizon)
Just Enough Items (JEI) (by mezz)
ZeroCore 2 (by ZeroNoRyouki)
Mekanism Additions (by bradyaidanc)
Phi (Psi addon) (by GDavid04)
Magical Psi: Redux (by TheIllusiveC4)
ConnectedTexturesMod (by tterrag1098)
InsaneLib (by Insane96MCP)
Ender Storage 1.8.+ (by covers1624)
Environmental Tech (by ValkyrieofNight)
Bad Wither No Cookie - Reloaded (by Kreezxil)
Architectury API (Forge) (by shedaniel)
FTB Library (Forge) (by FTB)
FTB Teams (Forge) (by FTB)
Immersive Portals (for Forge) (by qouteall)
Real Music discs (by Ip_make)
Cloth Config API (Forge) (by shedaniel)
Waystones (by BlayTheNinth)
ValkyrieLib (by ValkyrieofNight)
Mass Inscriber (by gliscowo)
Stoneholm, Underground Villages (Forge) (by TheGrimsey)
More Mekanism Processing (by 지젤쟝다)
BetterEnd (Forge) (by Beethoven92)
Citadel (by alex_khaan)
SwingThroughGrass (by exidex)
Environmental Core (by ValkyrieofNight)
Origins Reservoir 2 (Forge/Fabric) (by TheImperiumCentral)
Immersive Engineering (by BluSunrize)
Biomes O' Plenty (by Forstride)
Chisel (by tterrag1098)
LazierAE2 (by DamnRelentless)
Immersive Petroleum (by Flaxbeard)
Macaw's Trapdoors (by sketch_macaw)
Psi (by Vazkii)
Patchouli (by Vazkii)
YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
Caelus API (Forge) (by TheIllusiveC4)
PneumaticCraft: Repressurized (by desht_08)
JourneyMap (by techbrew)
Blood Magic (by WayofTime)
PlantTech 2 (by chrisland)
Morpheus (by Quetzi)
Macaw's Windows (by sketch_macaw)
Extreme Reactors (by ZeroNoRyouki)
OpenBlocks Elevator (by vsngarcia)
Mekanism (by bradyaidanc)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
Corrupted Witherskeleton Boss Mod (by HygerianYT)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Botania (by Vazkii)
Skin Layers 3D (Fabric/Forge) (by tr9zw)
CodeChicken Lib 1.8.+ (by covers1624)
Psionic Peripherals (by Dudblockman)
Thermal Foundation (by TeamCoFH)
Space-BossTools (by mrscauthd)
Akisephila's Bosses (by Akisephila)
Amogus Boss Mod (by nyaanez44)
CoFH Core (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
Obfuscate (by MrCrayfish)
Simple Discord RPC [Forge/Fabric] (by hypherionsa)
Macaw's Fences and Walls (by sketch_macaw)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Macaw's Bridges (by sketch_macaw)
Ore Excavation (by Funwayguy)
Voidscape (by Tamaized)
Origins (Forge) (by EdwinMindcraft)
Pehkui (by Virtuoel)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
Clumps (by Jaredlll08)
The Twilight Forest (by Benimatic)
Iron Chests (by ProgWML6)
Mob Grinding Utils (by vadis365)
Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)
FTB Chunks (Forge) (by FTB)
Fast Leaf Decay (by olafskiii)
Curios API (Forge) (by TheIllusiveC4)
The Legend of Herobrine (Forge 1.16.5) (by AlexMacLean)
The Whisperer (by pedrothedevelopper)
YUNG's Better Portals (Forge) (by YUNGNICKYOUNG)
Simply Backpacks (by Flanks255)
Better Bedrock Generator (by JayJay1989BE)
Corpse (by henkelmax)
Macaw's Roofs (by sketch_macaw)
Immersive Posts (by TwistedGate)
Alex's Mobs (by alex_khaan)
Applied Energistics 2 (by AlgorithmX2)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Mouse Tweaks (by YaLTeR)
Macaw's Doors (by sketch_macaw)
Numina (by machinemuse)
Controlling (by Jaredlll08)
Modular Powersuits (by machinemuse)
♪ Alex's Mobs Battle Music ♪ (by my_name_is_krossy)
Origins Collection 1 (Forge/Fabric) (by TheImperiumCentral)
Mekanism: Addons (by MorningSageX)

### Mod Version

-All on latest's stable releases  for 1.16.5

### Magma Version

1.16.5-36.2.8-977cc46-DEV

### OS

Windows

### Relevant log output

```shell
[16:20:33] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.8-977cc46-DEV, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[16:20:33] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 11.0.11 by Oracle Corporation
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/C:/Users/talon/Desktop/1.16.5%20community%20modpack%20setup/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[16:20:34] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[16:20:34] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/talon/Desktop/1.16.5%20community%20modpack%20setup/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[16:20:35] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[16:20:35] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[16:20:35] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[16:20:35] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[16:20:35] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[16:20:35] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[16:20:35] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[16:20:35] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[16:20:35] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[16:20:35] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[16:20:36] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[16:20:36] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[16:20:36] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.qouteall.hiding_in_the_bushes.MyMixinConnector]
[16:20:36] [main/INFO] [Portal/]: Invoking Mixin Connector
[16:20:36] [main/ERROR] [mixin/]: Mixin config imm_ptl_mixins.json does not specify "minVersion" property
[16:20:36] [main/ERROR] [mixin/]: Mixin config imm_ptl_mixins_forge.json does not specify "minVersion" property
[16:20:36] [main/ERROR] [mixin/]: Mixin config imm_ptl_peripheral_mixins.json does not specify "minVersion" property
[16:20:36] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
[16:20:36] [main/WARN] [mixin/]: Reference map 'massinscriber.refmap.json' for massinscriber.mixins.json could not be read. If this is a development environment you can ignore this message
[16:20:36] [main/WARN] [mixin/]: Reference map 'boss_tools.refmap.json' for boss_tools.mixins.json could not be read. If this is a development environment you can ignore this message
[16:20:36] [main/WARN] [mixin/]: Error loading class: top/theillusivec4/culinaryconstruct/common/item/CulinaryItemBase (java.lang.ClassNotFoundException: null)
[16:20:36] [main/WARN] [mixin/]: @Mixin target top.theillusivec4.culinaryconstruct.common.item.CulinaryItemBase was not found origins.forge.mixins.json:compat.cconstruct.CulinaryItemBaseMixin
[16:20:36] [main/WARN] [mixin/]: Error loading class: org/jwaresoftware/mcmods/vfp/common/VfpPantryItem (java.lang.ClassNotFoundException: null)
[16:20:36] [main/WARN] [mixin/]: @Mixin target org.jwaresoftware.mcmods.vfp.common.VfpPantryItem was not found origins.forge.mixins.json:compat.vfp.VfpPantryItemMixin
[16:20:38] [main/FATAL] [mixin/]: Mixin apply failed imm_ptl_peripheral_mixins.json:common.altius_world.MixinChunkStatus -> net.minecraft.world.chunk.ChunkStatus: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException 'static' modifier of handler method does not match target in net/minecraft/world/chunk/ChunkStatus::redirectBuildSurface [PREINJECT Applicator Phase -> imm_ptl_peripheral_mixins.json:common.altius_world.MixinChunkStatus -> Prepare Injections ->  -> handler$znf000$redirectBuildSurface(Lnet/minecraft/world/server/ServerWorld;Lnet/minecraft/world/gen/ChunkGenerator;Ljava/util/List;Lnet/minecraft/world/chunk/IChunk;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: 'static' modifier of handler method does not match target in net/minecraft/world/chunk/ChunkStatus::redirectBuildSurface [PREINJECT Applicator Phase -> imm_ptl_peripheral_mixins.json:common.altius_world.MixinChunkStatus -> Prepare Injections ->  -> handler$znf000$redirectBuildSurface(Lnet/minecraft/world/server/ServerWorld;Lnet/minecraft/world/gen/ChunkGenerator;Ljava/util/List;Lnet/minecraft/world/chunk/IChunk;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetModifiers(Injector.java:347) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.sanityCheck(CallbackInjector.java:387) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:237) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
        at net.minecraftforge.registries.GameData.init(GameData.java:177) ~[forge:?] {re:classloading}
        at net.minecraftforge.registries.GameData.<clinit>(GameData.java:132) ~[forge:?] {re:classloading}
        at net.minecraft.util.registry.Registry.forge(Registry.java:347) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.RegistryAccess,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.registry.Registry.forge(Registry.java:331) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.RegistryAccess,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.registry.Registry.<clinit>(Registry.java:140) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.RegistryAccess,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:41) ~[?:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:138) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.8-977cc46-DEV.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.8-977cc46-DEV.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.8-977cc46-DEV.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.8-977cc46-DEV.jar:?] {}
Exception in thread "main" [16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.reflect.InvocationTargetException
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:       at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:       ... 7 more
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at net.minecraftforge.registries.GameData.init(GameData.java:177)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at net.minecraftforge.registries.GameData.<clinit>(GameData.java:132)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at net.minecraft.util.registry.Registry.forge(Registry.java:347)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at net.minecraft.util.registry.Registry.forge(Registry.java:331)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at net.minecraft.util.registry.Registry.<clinit>(Registry.java:140)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:41)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    at net.minecraft.server.Main.main(Main.java:138)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:    ... 13 more
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imm_ptl_peripheral_mixins.json:common.altius_world.MixinChunkStatus] from phase [DEFAULT] in config [imm_ptl_peripheral_mixins.json] FAILED during APPLY
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:    ... 30 more
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: 'static' modifier of handler method does not match target in net/minecraft/world/chunk/ChunkStatus::redirectBuildSurface [PREINJECT Applicator Phase -> imm_ptl_peripheral_mixins.json:common.altius_world.MixinChunkStatus -> Prepare Injections ->  -> handler$znf000$redirectBuildSurface(Lnet/minecraft/world/server/ServerWorld;Lnet/minecraft/world/gen/ChunkGenerator;Ljava/util/List;Lnet/minecraft/world/chunk/IChunk;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetModifiers(Injector.java:347)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.sanityCheck(CallbackInjector.java:387)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:237)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[16:20:38] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]:    ... 30 more
```

**Comment by p928s1984** [comment]
Have the same issue any update? just tried the latest beta, still has the issue. 
Magma-1.16.5-36.2.23-a18dc70-DEV
