### ISSUE TITLE
[Bug]: mod incopatibility: infernal expansion, mining master and possibly other infernal studios' mods

### ISSUE THREAD

**Issue by kuba26038** [magmafoundation/Magma-1.16.x#183]
### What happened?

whenever i try to launch the server, it almost immeadietly shuts down. the last command prompt's messages are as follows:
![obraz](https://user-images.githubusercontent.com/81324988/142664033-081c130f-ef2b-4f23-94fb-ce790e2efbb3.png)

### Mods

the same thing happens for both of these mods:
miningmaster-1.16.5-2.0.0 
infernal-expansion-1.16.5-2.4.0

### Mod Version

miningmaster-1.16.5-2.0.0 
infernal-expansion-1.16.5-2.4.0

### Magma Version

forge-1.16.5-36.2.9-75c9e73-STABLE

### OS

Windows

### Relevant log output

```shell
[19lis2021 18:19:21.835] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.9-75c9e73-STABLE, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[19lis2021 18:19:21.839] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_301 by Oracle Corporation
[19lis2021 18:19:22.476] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[19lis2021 18:19:22.515] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/bynie/Desktop/eeee/magma/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[19lis2021 18:19:23.839] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[19lis2021 18:19:24.473] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [org.infernalstudios.infernalexp.mixin.MixinConnector]
[19lis2021 18:19:24.475] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[19lis2021 18:19:24.477] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.integral.enigmaticlegacy.MixinConnector]
[19lis2021 18:19:24.479] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [eutros.framedcompactdrawers.MixinConnector]
[19lis2021 18:19:24.481] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.performant.coremod.mixin.Connector]
[19lis2021 18:19:24.487] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[19lis2021 18:19:24.569] [main/WARN] [mixin/]: Reference map 'ragnagoblin.refmap.json' for ragnagoblin.mixins.json could not be read. If this is a development environment you can ignore this message
[19lis2021 18:19:24.585] [main/WARN] [mixin/]: Reference map 'brazier-forge-refmap.json' for brazier-forge.mixins.json could not be read. If this is a development environment you can ignore this message
[19lis2021 18:19:24.614] [main/WARN] [mixin/]: Reference map 'wlrs.refmap.json' for wlrs.mixin.json could not be read. If this is a development environment you can ignore this message
[19lis2021 18:19:24.617] [main/WARN] [mixin/]: Reference map 'globaldataandresourcepacks.refmap.json' for globaldataandresourcepacks.mixins.json could not be read. If this is a development environment you can ignore this message
[19lis2021 18:19:24.620] [main/WARN] [mixin/]: Reference map 'nethers_delight.refmap.json' for nethers_delight.mixins.json could not be read. If this is a development environment you can ignore this message
[19lis2021 18:19:24.694] [main/INFO] [com.performant.coremod.Performant/]: Performant configs loaded
[19lis2021 18:19:24.892] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[19lis2021 18:19:25.021] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching ItemStack#onItemUse
[19lis2021 18:19:25.455] [main/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/tileentity/SignTileEntityRenderer for invalid dist DEDICATED_SERVER
[19lis2021 18:19:25.456] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/tileentity/SignTileEntityRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/tileentity/SignTileEntityRenderer for invalid dist DEDICATED_SERVER)
[19lis2021 18:19:25.457] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.tileentity.SignTileEntityRenderer was not found farmersdelight.mixins.json:CanvasSignMaterialMixin
[19lis2021 18:19:25.630] [main/WARN] [mixin/]: Error loading class: biomesoplenty/common/world/BOPBiomeProvider (java.lang.ClassNotFoundException: null)
[19lis2021 18:19:25.659] [main/WARN] [mixin/]: Error loading class: com/ferreusveritas/dynamictrees/worldgen/BiomeRadiusCoordinator (java.lang.ClassNotFoundException: null)
[19lis2021 18:19:25.661] [main/WARN] [mixin/]: Error loading class: com/ferreusveritas/dynamictrees/worldgen/TreeGenerator (java.lang.ClassNotFoundException: null)
[19lis2021 18:19:25.752] [main/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/IngameGui for invalid dist DEDICATED_SERVER
[19lis2021 18:19:25.752] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/IngameGui (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/IngameGui for invalid dist DEDICATED_SERVER)
[19lis2021 18:19:25.754] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.IngameGui was not found conjuring.mixins.json:InGameHudMixin
[19lis2021 18:19:25.756] [main/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/ItemRenderer for invalid dist DEDICATED_SERVER
[19lis2021 18:19:25.756] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/ItemRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/ItemRenderer for invalid dist DEDICATED_SERVER)
[19lis2021 18:19:25.757] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.ItemRenderer was not found conjuring.mixins.json:ItemRendererMixin
[19lis2021 18:19:25.760] [main/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/particle/ParticleManager for invalid dist DEDICATED_SERVER
[19lis2021 18:19:25.760] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/particle/ParticleManager (java.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/ParticleManager for invalid dist DEDICATED_SERVER)
[19lis2021 18:19:25.761] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.particle.ParticleManager was not found conjuring.mixins.json:ParticleManagerAccessor
[19lis2021 18:19:25.768] [main/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER
[19lis2021 18:19:25.769] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/WorldRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER)
[19lis2021 18:19:25.769] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.WorldRenderer was not found conjuring.mixins.json:SpawnerParticleMixin
[19lis2021 18:19:25.778] [main/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER
[19lis2021 18:19:25.778] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/WorldRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER)
[19lis2021 18:19:25.779] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.WorldRenderer was not found conjuring.mixins.json:WorldRendererMixin
[19lis2021 18:19:25.915] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching DataPackRegistries#<init>
[19lis2021 18:19:25.930] [main/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
[19lis2021 18:19:25.931] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/entity/player/ClientPlayerEntity (java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER)
[19lis2021 18:19:25.932] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.entity.player.ClientPlayerEntity was not found ars_nouveau.mixins.json:ClientElytraMixin
[19lis2021 18:19:26.137] [main/WARN] [mixin/]: Error loading class: shadows/apotheosis/ench/table/ApothEnchantContainer (java.lang.ClassNotFoundException: null)
[19lis2021 18:19:26.147] [main/WARN] [mixin/]: Error loading class: net/darkhax/darkutils/features/charms/CharmEffects (java.lang.ClassNotFoundException: null)
[19lis2021 18:19:26.149] [main/WARN] [mixin/]: Error loading class: com/brandon3055/csg/ModEventHandler (java.lang.ClassNotFoundException: null)
[19lis2021 18:19:26.174] [main/INFO] [com.performant.coremod.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[19lis2021 18:19:26.179] [main/INFO] [com.performant.coremod.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.world.WorldMixin as config disables it.
[19lis2021 18:19:26.198] [main/INFO] [com.performant.coremod.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
[19lis2021 18:19:27.322] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[19lis2021 18:19:27.323] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[19lis2021 18:19:27.323] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[19lis2021 18:19:27.324] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[19lis2021 18:19:27.325] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[19lis2021 18:19:27.325] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[19lis2021 18:19:27.326] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[19lis2021 18:19:27.326] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[19lis2021 18:19:27.327] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[19lis2021 18:19:27.327] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.reflect.InvocationTargetException
[19lis2021 18:19:27.328] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19lis2021 18:19:27.328] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19lis2021 18:19:27.329] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19lis2021 18:19:27.329] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19lis2021 18:19:27.330] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[19lis2021 18:19:27.330] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[19lis2021 18:19:27.331] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 7 more
[19lis2021 18:19:27.331] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[19lis2021 18:19:27.332] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[19lis2021 18:19:27.332] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[19lis2021 18:19:27.333] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[19lis2021 18:19:27.335] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[19lis2021 18:19:27.336] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[19lis2021 18:19:27.336] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[19lis2021 18:19:27.337] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[19lis2021 18:19:27.337] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[19lis2021 18:19:27.338] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[19lis2021 18:19:27.338] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[19lis2021 18:19:27.339] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19lis2021 18:19:27.340] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.server.MinecraftServer.<clinit>(MinecraftServer.java:187)
[19lis2021 18:19:27.340] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.server.Main.main(Main.java:108)
[19lis2021 18:19:27.341] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[19lis2021 18:19:27.342] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method IE_setCustomFireFromLava(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in infernal-expansion.mixins.json:common.MixinEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap infernal-expansion.refmap.json
[19lis2021 18:19:27.342] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[19lis2021 18:19:27.343] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[19lis2021 18:19:27.343] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[19lis2021 18:19:27.344] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[19lis2021 18:19:27.344] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[19lis2021 18:19:27.344] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[19lis2021 18:19:27.345] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[19lis2021 18:19:27.346] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[19lis2021 18:19:27.346] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 25 more
```

**Comment by khankul** [comment]
I've had this with Infernal Expansion too.
