### ISSUE TITLE
FTBLibrary not Supported

### ISSUE THREAD

**Issue by hiroashikawa** [magmafoundation/Magma-1.16.x#184]
Fresh Installation of Magma 1.16.5 (Version: v75c9e73 - Date: 2021-11-17T07:18:01Z) with current mods:

OS: Windows Server 2019 x86_64

**architectury-1.24.35-forge
ftb-library-forge-1605.3.4-build.87
ftb-teams-forge-1605.2.3-build.38
ftb-ranks-forge-1605.1.5-build.16
voicechat-forge-1.16.5-1.8.0
ftb-chunks-forge-1605.3.2-build.81**

Latest Java 8.

Results with this error:
`[17:33:49] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        FTB Library (ftblibrary) has failed to load correctly
§7java.lang.ExceptionInInitializerError: null
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:272) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:239) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:197) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:141) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [server.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [server.jar:?] {}`

**Comment by Cixon** [comment]
update Architectury to v1.25.36 and FTBTeams to v1605.2.3-b40. I tried this and I had no issue with Magma. Please close this issue once tested.
