### ISSUE TITLE
[Bug]: Launch failed.

### ISSUE THREAD

**Issue by colinxu2020** [magmafoundation/Magma-1.16.x#185]
### What happened?

Happend: Server start failed. crash-reports: [postebin](https://pastebin.ubuntu.com/p/dkx92vnGqW/)
Except: Sucess start.

### Mods

None

### Mod Version

None

### Magma Version

1.16.x-75c9e73

### OS

Windows

### Relevant log output

```shell
[11:00:18] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.9-75c9e73-STABLE, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[11:00:18] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 11.0.9 by AdoptOpenJDK
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/E:/minecraft/%e6%9c%8d%e5%8a%a1%e5%99%a8/%e8%81%94%e6%9c%ba/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[11:00:19] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[11:00:19] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/E:/minecraft/%e6%9c%8d%e5%8a%a1%e5%99%a8/%e8%81%94%e6%9c%ba/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[11:00:20] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[11:00:20] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[11:00:20] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[11:00:20] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
[11:00:27] [modloading-worker-1/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 36.2.9-75c9e73-STABLE, for MC 1.16.5 with MCP 20210115.111550
[11:00:27] [modloading-worker-1/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v36.2.9-75c9e73-STABLE Initialized
[11:00:28] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[11:00:31] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: AHEAD Current: 36.2.9-75c9e73-STABLE Target: null
[11:00:32] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:00:33] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, forge-1.16.5-36.2.9-75c9e73-STABLE-universal.jar, bukkit
[11:00:35] [Worker-Main-14/INFO] [minecraft/RecipeManager]: Loaded 7 recipes
[11:00:40] [main/INFO] [or.ma.ma.pa.PatcherManager/]: 2 patches loaded!
[11:00:40] [main/INFO] [or.ma.ma.pa.PatcherManager/]: Dynmap [Fix Dynamp not finding the correct nms class] loaded
[11:00:40] [main/INFO] [or.ma.ma.pa.PatcherManager/]: Essentials [Fixes for Essentials] loaded
[11:00:40] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.16.5
[11:00:40] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
[11:00:40] [Server thread/INFO] [Minecraft/]: This server is running Magma version git-Magma-1.16.5-36.2.9-75c9e73-STABLE (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[11:00:41] [Server thread/WARN] [/]: java.lang.IllegalAccessException: 类 java/lang/invoke/MethodHandle 非法访问类 org/bukkit/block/banner/PatternType 的成员 "private"
[11:00:41] [Server thread/WARN] [/]:    at java.base/java.lang.invoke.FieldHandle.finishFieldInitialization(FieldHandle.java:69)
[11:00:41] [Server thread/WARN] [/]:    at java.base/java.lang.invoke.FieldHandle.<init>(FieldHandle.java:36)
[11:00:41] [Server thread/WARN] [/]:    at java.base/java.lang.invoke.StaticFieldSetterHandle.<init>(StaticFieldSetterHandle.java:37)
[11:00:41] [Server thread/WARN] [/]:    at java.base/java.lang.invoke.MethodHandles$Lookup.findStaticSetter(MethodHandles.java:974)
[11:00:41] [Server thread/WARN] [/]:    at org.magmafoundation.magma.util.EnumHelper$Java9.setFailsafeFieldValue(EnumHelper.java:234)
[11:00:42] [Server thread/WARN] [/]:    at org.magmafoundation.magma.util.EnumHelper$Java9.addEnum(EnumHelper.java:293)
[11:00:42] [Server thread/WARN] [/]:    at org.magmafoundation.magma.util.EnumHelper.addEnum(EnumHelper.java:52)
[11:00:42] [Server thread/WARN] [/]:    at org.magmafoundation.magma.forge.ForgeInject.lambda$addForgeBannerPatters$5(ForgeInject.java:164)
[11:00:42] [Server thread/WARN] [/]:    at org.magmafoundation.magma.forge.ForgeInject$$Lambda$4620/0x000000007eb74f60.accept(Unknown Source)
[11:00:42] [Server thread/WARN] [/]:    at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:109)
[11:00:42] [Server thread/WARN] [/]:    at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:622)
[11:00:42] [Server thread/WARN] [/]:    at org.magmafoundation.magma.forge.ForgeInject.addForgeBannerPatters(ForgeInject.java:163)
[11:00:42] [Server thread/WARN] [/]:    at org.magmafoundation.magma.forge.ForgeInject.injectForge(ForgeInject.java:85)
[11:00:42] [Server thread/WARN] [/]:    at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:153)
[11:00:42] [Server thread/WARN] [/]:    at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:19)
[11:00:42] [Server thread/WARN] [/]:    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:178)
[11:00:42] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825)
[11:00:42] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286)
[11:00:42] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer$$Lambda$4423/0x000000007dc6c3f0.run(Unknown Source)
[11:00:42] [Server thread/WARN] [/]:    at java.base/java.lang.Thread.run(Thread.java:836)
[11:00:43] [Server thread/WARN] [/]: Caused by: java.lang.IllegalAccessError: 类 java/lang/invoke/MethodHandle 非法访问 类 org/bukkit/block/banner/PatternType 的成员 "private"
[11:00:43] [Server thread/WARN] [/]:    at java.base/java.lang.invoke.FieldHandle.finishFieldInitialization(FieldHandle.java:65)
[11:00:43] [Server thread/WARN] [/]:    ... 19 more
[11:00:43] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.RuntimeException: 类 java/lang/invoke/MethodHandle 非法访问类 org/bukkit/block/banner/PatternType 的成员 "private"
        at org.magmafoundation.magma.util.EnumHelper$Java9.addEnum(EnumHelper.java:299) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.util.EnumHelper.addEnum(EnumHelper.java:52) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.forge.ForgeInject.lambda$addForgeBannerPatters$5(ForgeInject.java:164) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.forge.ForgeInject$$Lambda$4620/0x000000007eb74f60.accept(Unknown Source) ~[?:?] {}
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:109) ~[?:?] {}
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:622) ~[?:?] {}
        at org.magmafoundation.magma.forge.ForgeInject.addForgeBannerPatters(ForgeInject.java:163) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.forge.ForgeInject.injectForge(ForgeInject.java:85) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:153) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:19) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:178) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer$$Lambda$4423/0x000000007dc6c3f0.run(Unknown Source) [?:?] {}
        at java.lang.Thread.run(Thread.java:836) [?:?] {}
Caused by: java.lang.IllegalAccessException: 类 java/lang/invoke/MethodHandle 非法访问类 org/bukkit/block/banner/PatternType 的成员 "private"
        at java.lang.invoke.FieldHandle.finishFieldInitialization(FieldHandle.java:69) ~[?:?] {}
        at java.lang.invoke.FieldHandle.<init>(FieldHandle.java:36) ~[?:?] {}
        at java.lang.invoke.StaticFieldSetterHandle.<init>(StaticFieldSetterHandle.java:37) ~[?:?] {}
        at java.lang.invoke.MethodHandles$Lookup.findStaticSetter(MethodHandles.java:974) ~[?:?] {}
        at org.magmafoundation.magma.util.EnumHelper$Java9.setFailsafeFieldValue(EnumHelper.java:234) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.util.EnumHelper$Java9.addEnum(EnumHelper.java:293) ~[forge:?] {re:classloading}
        ... 14 more
Caused by: java.lang.IllegalAccessError: 类 java/lang/invoke/MethodHandle 非法访问类 org/bukkit/block/banner/PatternType 的成员 "private"
        at java.lang.invoke.FieldHandle.finishFieldInitialization(FieldHandle.java:65) ~[?:?] {}
        at java.lang.invoke.FieldHandle.<init>(FieldHandle.java:36) ~[?:?] {}
        at java.lang.invoke.StaticFieldSetterHandle.<init>(StaticFieldSetterHandle.java:37) ~[?:?] {}
        at java.lang.invoke.MethodHandles$Lookup.findStaticSetter(MethodHandles.java:974) ~[?:?] {}
        at org.magmafoundation.magma.util.EnumHelper$Java9.setFailsafeFieldValue(EnumHelper.java:234) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.util.EnumHelper$Java9.addEnum(EnumHelper.java:293) ~[forge:?] {re:classloading}
        ... 14 more
[11:00:43] [Server thread/ERROR] [minecraft/MinecraftServer]:   Cause of unexpected exception was
java.lang.IllegalAccessException: 类 java/lang/invoke/MethodHandle 非法访问类 org/bukkit/block/banner/PatternType 的成员 "private"
        at java.lang.invoke.FieldHandle.finishFieldInitialization(FieldHandle.java:69) ~[?:?] {}
        at java.lang.invoke.FieldHandle.<init>(FieldHandle.java:36) ~[?:?] {}
        at java.lang.invoke.StaticFieldSetterHandle.<init>(StaticFieldSetterHandle.java:37) ~[?:?] {}
        at java.lang.invoke.MethodHandles$Lookup.findStaticSetter(MethodHandles.java:974) ~[?:?] {}
        at org.magmafoundation.magma.util.EnumHelper$Java9.setFailsafeFieldValue(EnumHelper.java:234) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.util.EnumHelper$Java9.addEnum(EnumHelper.java:293) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.util.EnumHelper.addEnum(EnumHelper.java:52) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.forge.ForgeInject.lambda$addForgeBannerPatters$5(ForgeInject.java:164) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.forge.ForgeInject$$Lambda$4620/0x000000007eb74f60.accept(Unknown Source) ~[?:?] {}
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:109) ~[?:?] {}
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:622) ~[?:?] {}
        at org.magmafoundation.magma.forge.ForgeInject.addForgeBannerPatters(ForgeInject.java:163) ~[forge:?] {re:classloading}
        at org.magmafoundation.magma.forge.ForgeInject.injectForge(ForgeInject.java:85) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:153) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:19) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:178) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer$$Lambda$4423/0x000000007dc6c3f0.run(Unknown Source) [?:?] {}
        at java.lang.Thread.run(Thread.java:836) [?:?] {}
Caused by: java.lang.IllegalAccessError: 类 java/lang/invoke/MethodHandle 非法访问类 org/bukkit/block/banner/PatternType 的成员 "private"
        at java.lang.invoke.FieldHandle.finishFieldInitialization(FieldHandle.java:65) ~[?:?] {}
        ... 19 more
[11:00:43] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 23410cc7-0ddc-4e66-b303-b95e668e96a2
> 2021-11-20 11:00:43,452 Server thread ERROR File not found in file system or classpath: log4j2_magma.xml
2021-11-20 11:00:43,469 Server thread ERROR Reconfiguration failed: No configuration found for 'f7ee9a4' at 'null' in 'null'
```

**Comment by AwesomeDude091** [comment]
Use java 8
