### ISSUE TITLE
DungeonCrawl fails to load

### ISSUE THREAD

**Issue by Spoons** [magmafoundation/Magma-1.16.x#194]
### What happened?

Throws a null pointer exception at server start.

### Mods

Valhelsia 3 + DungeonCrawl

### Mod Version

abnormals_core-1.16.5-3.3.0.jar
abnormals_delight-1.16.5-1.2.0.jar
absentbydesign-1.16.5-1.5.1.jar
Abundance-1.16.5-1.0.5.jar
advancedperipherals-1.16.5-0.7.3r.jar
AI-Improvements-1.16.2-0.3.0.jar
aiotbotania-1.16.5-1.8.4.jar
AkashicTome-1.4-16.jar
alexsmobs-1.12.1.jar
allurement-1.16.5-1.2.0.jar
Apotheosis-1.16.5-4.8.2.jar
appleskin-forge-mc1.16.x-2.1.0.jar
Aquaculture-1.16.5-2.1.21.jar
archers_paradox-1.16.5-1.3.1.jar
architectury-1.24.35-forge.jar
Artifacts-1.16.5-2.10.3.jar
astralsorcery-1.16-1.16.5-1.13.12.jar
atmospheric-1.16.5-3.1.0.jar
Atum-1.16.5-2.2.8.jar
AutoRegLib-1.6-49.jar
autumnity-1.16.5-2.1.1.jar
bamboo_blocks-1.16.5-3.0.0.jar
Bayou-Blues-1.16.5-1.0.5.jar
BedBenefits-1.16.5-5.0.4.jar
bedspreads-forge-1.16.5-5.1.0.3.jar
berry_good-1.16.5-4.1.1.jar
Better-Badlands-1.16.5-2.0.3.jar
betterbiomeblend-1.16.4-1.2.9-forge.jar
BetterBurning-1.16.5-6.0.7.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
betterendforge-1.16.5-1.6.3.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
BetterStrongholds-1.16.4-1.2.1.jar
BetterTitleScreen-1.16.4-1.10.2.jar
BiomesOPlenty-1.16.5-13.1.0.482-universal.jar
blockcarpentry-1.16-0.4.0.jar
BloodMagic-1.16.4-3.1.5-25.jar
blue_skies-1.16.5-1.1.3.jar
Bookshelf-Forge-1.16.5-10.3.29.jar
Botania-1.16.5-419.jar
buildinggadgets-1.16.5-3.8.2.jar
buzzier_bees-1.16.5-3.0.1.jar
bwncr-1.16.5-3.10.16.jar
caelus-forge-1.16.5-2.1.3.1.jar
carryon-1.16.5-1.15.5.15.jar
catjammies-1.1.0.jar
cavebiomeapi-1.16.5-1.4.0.jar
cc-tweaked-1.16.5-1.98.2.jar
chiselsandbits-1.0.42-ALPHA.jar
chocolate-1.3.0-1.16.4.jar
chunkloaders-1.1.7-mc1.16.5.jar
citadel-1.8.1-1.16.5.jar
ClientTweaks_1.16.3-5.3.0.jar
cloth-config-4.11.26-forge.jar
Clumps-6.0.0.27.jar
CodeChickenLib-1.16.5-4.0.3.434-universal.jar
cofh_core-1.16.5-1.3.1.jar
comforts-forge-1.16.5-4.0.1.3.jar
connectiblechains-1.2.0.jar
connectivity-2.3-1.16.5.jar
cookielicious-1.16.5-1.4.3.jar
CookingForBlockheads_1.16.5-9.3.4.jar
CosmeticArmorReworked-1.16.5-v4.jar
CraftingTweaks_1.16.5-12.2.1.jar
createaddition-1.16.5-20211023a.jar
create-mc1.16.5_v0.3.2f.jar
CreativeCore_v2.2.1_mc1.16.5.jar
CTM-MC1.16.1-1.1.2.6.jar
curioofundying-forge-1.16.5-5.2.0.0.jar
curios-forge-1.16.5-4.0.5.3.jar
CuriosQuarkOBP-1.16.5-1.0.2.jar
'Curious Armor Stands-1.16.5-2.1.2.jar'
curiouselytra-forge-1.16.5-4.0.2.3.jar
curiousshulkerboxes-forge-1.16.5-4.0.1.0.jar
customizableelytra-1.16.4-1.5.7.jar
darkerdepths-1.16.5-1.1.4.jar
DarkUtilities-1.16.5-8.0.11.jar
dash-1.16.4-1.0.1.jar
decorative_blocks-1.16.4-1.7.2.jar
decorative_blocks_abnormals-1.2.jar
differentiate-1.16.5-0.5.3.jar
DrawersTooltip-1.16.2-2.1.1.jar
Druidcraft-1.16.5-0.4.54.jar
DungeonCrawl-1.16.5-2.3.4.jar
dungeons_mobs-1.16.5-1.0.10.jar
dusk-1.4.jar
eidolon-0.2.7.jar
elevatorid-1.16.5-1.7.13.jar
endergetic-1.16.4-3.0.0.jar
EnderStorage-1.16.5-2.8.0.168-universal.jar
engineersdecor-1.16.4-1.1.14.jar
Enhanced-Mushrooms-1.16.5-3.0.9.jar
ensorcellation-1.16.5-1.3.1.jar
environmental-1.16.5-1.1.0.jar
etched-1.1.0-1.16.5-forge.jar
expandability-2.0.1-forge.jar
extlights-3.3.jar
extraboats-1.16.5-2.1.0.jar
fairylights-4.0.5-1.16.5.jar
FarmersDelight-1.16.5-0.5.1.jar
farsightedmobs-forge-1.16-1.1.jar
fastbenchminusreplacement-1.4.jar
fastfurnaceminusreplacement-1.1-1.16.3.jar
FastLeafDecay-v25.jar
ferritecore-2.1.0-forge.jar
fishingreal-1.16.3-1.0.0.jar
FluxNetworks-1.16.5-6.1.7.12.jar
flywheel-1.16-0.2.4.jar
forbidden_arcanus-16.2.0-beta-4.jar
Fruitful-1.16.5-2.1.0.jar
ftb-backups-2.1.2.2.jar
goblintraders-1.6.0-1.16.3.jar
iChunUtil-1.16.5-10.4.1.jar
ImmersiveEngineering-1.16.5-5.0.5-140.jar
ImmersivePetroleum-1.16.5-3.3.0-7.jar
immersiveposts-1.16.5-4.2.2.jar
incontrol-1.16-5.2.1.jar
industrial-foregoing-1.16.5-3.2.14.6-14.jar
ironchest-1.16.5-11.2.13.jar
JAOPCA-1.16.5-3.4.1.15.jar
jeed-1.16.5-1.3.jar
jei-1.16.5-7.7.1.129.jar
jeiintegration_1.16.5-7.0.1.15.jar
JustEnoughResources-1.16.5-0.12.1.128.jar
Kiwi-1.16.5-3.6.0.jar
KleeSlabs_1.16.5-9.2.1.jar
kubejs-blood-magic-1605.1.1-build.3.jar
kubejs-create-1605.1.2-build.7.jar
kubejs-forge-1605.3.18-build.152.jar
kubejs-immersive-engineering-1605.1.1-build.2.jar
kubejs-mekanism-1605.1.2-build.2.jar
lazydfu-0.1.3.jar
leap-1.16.4-1.1.1.jar
LibX-1.16.3-1.0.76.jar
Lollipop-1.16.5-3.2.9.jar
mannequins-1.0.1-1.16.5-forge.jar
mcw-bridges-1.0.6-mc1.16.5.jar
mcw-doors-1.0.3-mc1.16.5.jar
mcw-fences-1.0.1-mc1.16.5.jar
mcw-furniture-2.0.1-mc1.16.5.jar
mcw-roofs-2.0.1-mc1.16.5-4.jar
mcw-trapdoors-1.0.3-mc1.16.5.jar
mcw-windows-2.0.0-mc1.16.5.jar
Mekanism-1.16.5-10.0.22.449.jar
MekanismAdditions-1.16.5-10.0.22.449.jar
MekanismGenerators-1.16.5-10.0.22.449.jar
MekanismTools-1.16.5-10.0.22.449.jar
mgui-1.16.5-3.3.0.jar
mightyarchitect-mc1.16.3_v0.5.jar
minecolonies-1.0.87-ALPHA-universal.jar
mining_helmet-1.16.5-2.0.1.jar
MouseTweaks-2.14-mc1.16.2.jar
mowziesmobs-1.5.19.jar
mysticalworld-1.16.5-0.3.5.23.jar
MythicBotany-1.16.5-1.4.14.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
neapolitan-1.16.5-2.1.0.jar
'Neat 1.7-27.jar'
neoncraft-2.0.jar
netheritehorsearmor-1.7.jar
nethers_delight-2.1.jar
Notes-1.16.5-1.2.3.jar
observerlib-1.16.5-1.5.3.jar
OpenLoader-1.16.5-9.0.3.jar
PackMenu-1.16.5-2.5.0.jar
paintings-1.16.4-7.0.0.1.jar
Patchouli-1.16.4-53.2.jar
peculiars-1.16.5-2.0.0.jar
performant-1.16.2-5-3.72m.jar
personality-1.16.5-1.0.2.jar
pitg-1.16.5-2.0.1.jar
Placebo-1.16.5-4.6.0.jar
polymorph-forge-1.16.5-0.25.jar
Powah-1.16.5-2.3.16.jar
'Psi 1.16-97.jar'
QuarkOddities-1.16.3.jar
Quark-r2.4-319.jar
randompatches-2.4.4-forge.jar
refinedstorage-1.9.15.jar
refinedstorageaddons-0.7.3.jar
rhino-forge-1605.1.4-build.67.jar
rsrequestify-1.16.5-2.1.4.jar
Runelic-1.16.5-7.0.2.jar
savageandravage-1.16.5-3.1.0.jar
scuba-gear-1.16.5-1.0.3.jar
seasonals-1.16.5-2.0.0.jar
selene-1.16.5-1.8.1.jar
serverconfigupdater-1.3.jar
ServerTabInfo-1.16.4-1.3.3.jar
SnowRealMagic-1.16.4-2.7.2.jar
snowundertrees-1.16.5-v1.3.jar
sounddeviceoptions-1.4.3.jar
spark-forge.jar
step-1.16.4-1.1.0.jar
StorageDrawers-1.16.3-8.3.0.jar
structure_gel-1.16.5-1.7.8.jar
structurize-0.13.252-ALPHA-universal.jar
supermartijn642configlib-1.0.9-mc1.16.jar
supplementaries-1.16.5-0.17.7.jar
swingthroughgrass-1.16.4-1.5.3.jar
tetra-1.16.5-3.18.0.jar
tetranomicon-1.3.jar
tetrapak-1.16.5-0.3.3.jar
the-conjurer-1.16.4-1.0.13.jar
titanium-1.16.5-3.2.8.5-20.jar
tomes-1.2.jar
ToolStats-1.16.5-6.0.4.jar
torchmaster-2.3.8.jar
torchslabmod-1.16.4_v1.6.19.jar
Transport-1.16.5-3.7.0.jar
TrashSlot_1.16.3-12.2.1.jar
twilightforest-1.16.5-4.0.546-universal.jar
upgrade_aquatic-1.16.5-3.1.0.jar
valhelsia_core-16.0.13a.jar
valhelsia_structures-1.16.5-0.1.6.jar
valhelsia_tweaks-16.0.9.jar
Waddles-1.16.5-0.8.13.jar
Waystones_1.16.5-7.6.3.jar
windowlogging-mc1.16.3_v0.0.4.jar
Xaeros_Minimap_21.20.0_Forge_1.16.5.jar
XaerosWorldMap_1.18.0_Forge_1.16.5.jar
xercamusic-1.16.5-1.4.jar
YungsApi-1.16.4-Forge-13.jar

### Magma Version

 magma-1.16.5-36.2.9-75c9e73-STABLE

### OS

Linux

### Relevant log output

```shell
nifest: NOSIGNATURE
	Crash Report UUID: e56b26f4-783b-4fa6-bdd6-49cfad58403e
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport:
java.lang.NullPointerException
	at org.bukkit.Bukkit.getName(Bukkit.java:100)
	at org.bukkit.craftbukkit.v1_16_R3.CraftCrashReport.call(CraftCrashReport.java:23)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:81)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:74)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:39)
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:243)
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85)
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51)
	at net.minecraft.server.Main.main(Main.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[22:40:00] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Dungeon Crawl (dungeoncrawl) has failed to load correctly
§7org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:272) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:239) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:197) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:141) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.9-75c9e73-STABLE.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.9-75c9e73-STABLE.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.9-75c9e73-STABLE.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.9-75c9e73-STABLE.jar:?] {}
Press enter to continue../ServerStart.sh: 22: read: arg count
```

**Comment by Spoons** [comment]
Issue is due to DungeonCrawl. Closing.
