### ISSUE TITLE
[mod incompat]: Mining Master - Server crash, Mixin errors.

### ISSUE THREAD

**Issue by Cixon** [magmafoundation/Magma-1.16.x#206]
### What happened?

Mixins from Mining Master cause complications with Magma's server start-up.

### Mods

Mining Master
https://www.curseforge.com/minecraft/mc-mods/mining-master

### Mod Version

v2.1.0

### Magma Version

717036a-DEV

### OS

Windows

### Relevant log output

```shell
[18Dec2021 20:58:04.496] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.19-717036a-DEV, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[18Dec2021 20:58:04.499] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_312 by Oracle Corporation
[18Dec2021 20:58:04.817] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18Dec2021 20:58:04.860] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/container/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[18Dec2021 20:58:05.870] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 19:65 token recognition error at: ';'
[18Dec2021 20:58:06.694] [main/ERROR] [mixin/]: Mixin config unionlib.mixins.json does not specify "minVersion" property
[18Dec2021 20:58:06.753] [main/ERROR] [mixin/]: Mixin config mixins.terrestria.json does not specify "minVersion" property
[18Dec2021 20:58:06.755] [main/ERROR] [mixin/]: Mixin config mixins.terrestria.pathing.json does not specify "minVersion" property
[18Dec2021 20:58:06.757] [main/ERROR] [mixin/]: Mixin config mixins.terrestria.bugfix.json does not specify "minVersion" property
[18Dec2021 20:58:06.836] [main/ERROR] [mixin/]: Mixin config mixins.terraform-biome-builder.json does not specify "minVersion" property
[18Dec2021 20:58:06.839] [main/ERROR] [mixin/]: Mixin config mixins.terraform-dirt.json does not specify "minVersion" property
[18Dec2021 20:58:06.844] [main/ERROR] [mixin/]: Mixin config mixins.terraform-leaves.json does not specify "minVersion" property
[18Dec2021 20:58:06.848] [main/ERROR] [mixin/]: Mixin config mixins.terraform-signs.json does not specify "minVersion" property
[18Dec2021 20:58:06.852] [main/ERROR] [mixin/]: Mixin config mixins.terraform-overworld-biome-extensions.json does not specify "minVersion" property
[18Dec2021 20:58:06.854] [main/ERROR] [mixin/]: Mixin config mixins.terraform-tree-api-v1.json does not specify "minVersion" property
[18Dec2021 20:58:06.855] [main/ERROR] [mixin/]: Mixin config mixins.terraform-utils.json does not specify "minVersion" property
[18Dec2021 20:58:06.902] [main/ERROR] [mixin/]: Mixin config illagers_plus.mixin.json does not specify "minVersion" property
[18Dec2021 20:58:07.007] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [someoneelse.betternetherreforged.mixin.MixinConnector]
[18Dec2021 20:58:07.008] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.fuzs.goldenagecombat.mixin.MixinConnector]
[18Dec2021 20:58:07.010] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[18Dec2021 20:58:07.012] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [ca.spottedleaf.starlight.mixin.MixinConnector]
[18Dec2021 20:58:07.013] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [arekkuusu.offhandcombat.common.core.Connector]
[18Dec2021 20:58:07.019] [main/INFO] [someoneelse.betternetherreforged.BetterNether/]: Better Nether: Mixin Connected!
[18Dec2021 20:58:07.022] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
[18Dec2021 20:58:07.038] [main/WARN] [mixin/]: Reference map 'armorcurve.refmap.json' for wayfarer.mixins.json could not be read. If this is a development environment you can ignore this message
[18Dec2021 20:58:07.060] [main/WARN] [mixin/]: Reference map 'hostilevillages.refmap.json' for shieldmechanics.mixins.json could not be read. If this is a development environment you can ignore this message
[18Dec2021 20:58:07.089] [main/INFO] [RoadRunner Early Loading/]: Loaded rule configuration file for RoadRunner: 81 options available, 19 override(s) found
[18Dec2021 20:58:07.112] [main/WARN] [mixin/]: Reference map 'invisibilitycloak.refmap.json' for invisibilitycloak.mixins.json could not be read. If this is a development environment you can ignore this message
[18Dec2021 20:58:07.600] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/screen/WorldSelectionList$Entry (java.lang.ClassNotFoundException: null)
[18Dec2021 20:58:07.600] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.screen.WorldSelectionList$Entry was not found biomeidfixer.mixins.json:MixinWorldSelectionList
[18Dec2021 20:58:07.725] [main/INFO] [net.minecraftforge.coremod.CoreMod.somnia/COREMODLOG]: Patching class ServerPlayerEntity
[18Dec2021 20:58:08.487] [main/WARN] [mixin/]: Error loading class: top/theillusivec4/culinaryconstruct/common/item/CulinaryItemBase (java.lang.ClassNotFoundException: null)
[18Dec2021 20:58:08.487] [main/WARN] [mixin/]: @Mixin target top.theillusivec4.culinaryconstruct.common.item.CulinaryItemBase was not found origins.forge.mixins.json:compat.cconstruct.CulinaryItemBaseMixin
[18Dec2021 20:58:08.489] [main/WARN] [mixin/]: Error loading class: org/jwaresoftware/mcmods/vfp/common/VfpPantryItem (java.lang.ClassNotFoundException: null)
[18Dec2021 20:58:08.490] [main/WARN] [mixin/]: @Mixin target org.jwaresoftware.mcmods.vfp.common.VfpPantryItem was not found origins.forge.mixins.json:compat.vfp.VfpPantryItemMixin
[18Dec2021 20:58:08.529] [main/WARN] [mixin/]: Error loading class: biomesoplenty/common/world/BOPBiomeProvider (java.lang.ClassNotFoundException: null)
[18Dec2021 20:58:08.532] [main/WARN] [mixin/]: Error loading class: com/ferreusveritas/dynamictrees/worldgen/BiomeRadiusCoordinator (java.lang.ClassNotFoundException: null)
[18Dec2021 20:58:08.534] [main/WARN] [mixin/]: Error loading class: com/ferreusveritas/dynamictrees/worldgen/TreeGenerator (java.lang.ClassNotFoundException: null)
[18Dec2021 20:58:08.675] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.goal.GoalSelectorMixin' as rule 'mixin.ai.goal' (added by user configuration) disables it and children
[18Dec2021 20:58:08.676] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.LivingEntityMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.677] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.ServerWorldMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.678] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.WorldChunkMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.679] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.WorldMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.680] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.goals.FleeEntityGoalMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.681] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.goals.LookAtGoalMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.682] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.pathing.ChunkCacheMixin' as rule 'mixin.ai.pathing' (added by user configuration) disables it and children
[18Dec2021 20:58:08.683] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.pathing.LandPathNodeMakerMixin' as rule 'mixin.ai.pathing' (added by user configuration) disables it and children
[18Dec2021 20:58:08.684] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.pathing.MixinAbstractBlockState' as rule 'mixin.ai.pathing' (added by user configuration) disables it and children
[18Dec2021 20:58:08.685] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.pathing.MixinBlock' as rule 'mixin.ai.pathing' (added by user configuration) disables it and children
[18Dec2021 20:58:08.686] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.pathing.PathNodeNavigatorMixin' as rule 'mixin.ai.pathing' (added by user configuration) disables it and children
[18Dec2021 20:58:08.700] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.chunk_random.ServerWorldMixin' as rule 'mixin.alloc.chunk_random' (added by user configuration) disables it and children
[18Dec2021 20:58:08.700] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.chunk_random.WorldMixin' as rule 'mixin.alloc.chunk_random' (added by user configuration) disables it and children
[18Dec2021 20:58:08.701] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.chunk_ticking.ChunkTicketManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.702] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.706] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.entity_tracker.EntityTrackerMixin' as rule 'mixin.alloc.entity_tracker' (added by user configuration) disables it and children
[18Dec2021 20:58:08.707] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.enum_values.LivingEntityMixin' as rule 'mixin.alloc.enum_values' (added by user configuration) disables it and children
[18Dec2021 20:58:08.708] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.enum_values.PistonBlockMixin' as rule 'mixin.alloc.enum_values' (added by user configuration) disables it and children
[18Dec2021 20:58:08.709] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.enum_values.PistonHandlerMixin' as rule 'mixin.alloc.enum_values' (added by user configuration) disables it and children
[18Dec2021 20:58:08.710] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.enum_values.RedstoneWireBlockMixin' as rule 'mixin.alloc.enum_values' (added by user configuration) disables it and children
[18Dec2021 20:58:08.711] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.world_ticking.ServerWorldMixin' as rule 'mixin.alloc.world_ticking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.714] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'block.flatten_states.AbstractBlockStateMixin' as rule 'mixin.block.flatten_states' (added by user configuration) disables it and children
[18Dec2021 20:58:08.714] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'block.flatten_states.FluidStateMixin' as rule 'mixin.block.flatten_states' (added by user configuration) disables it and children
[18Dec2021 20:58:08.724] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'chunk.serialization.PackedIntegerArrayMixin' as rule 'mixin.chunk.serialization' (added by user configuration) disables it and children
[18Dec2021 20:58:08.725] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'chunk.serialization.PalettedContainerMixin' as rule 'mixin.chunk.serialization' (added by user configuration) disables it and children
[18Dec2021 20:58:08.726] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'collections.entity_filtering.TypeFilterableListMixin' as rule 'mixin.collections.entity_filtering' (added by user configuration) disables it and children
[18Dec2021 20:58:08.729] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'entity.data_tracker.use_arrays.DataTrackerMixin' as rule 'mixin.entity.data_tracker' (added by user configuration) disables it and children
[18Dec2021 20:58:08.733] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'entity.inactive_navigations.EntityNavigationMixin' as rule 'mixin.entity.inactive_navigations' (added by user configuration) disables it and children
[18Dec2021 20:58:08.735] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'entity.inactive_navigations.ServerWorldMixin' as rule 'mixin.entity.inactive_navigations' (added by user configuration) disables it and children
[18Dec2021 20:58:08.754] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'gen.fast_island_noise.NoiseChunkGeneratorMixin' as rule 'mixin.gen.fast_island_noise' (added by user configuration) disables it and children
[18Dec2021 20:58:08.755] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'gen.fast_island_noise.TheEndBiomeSourceMixin' as rule 'mixin.gen.fast_island_noise' (added by user configuration) disables it and children
[18Dec2021 20:58:08.779] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'world.block_entity_ticking.collections.WorldMixin' as rule 'mixin.world.block_entity_ticking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.780] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'world.block_entity_ticking.should_tick_cache.WorldMixin' as rule 'mixin.world.block_entity_ticking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.781] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'world.block_entity_ticking.support_cache.BlockEntityMixin' as rule 'mixin.world.block_entity_ticking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.782] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'world.block_entity_ticking.support_cache.WorldMixin' as rule 'mixin.world.block_entity_ticking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.820] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'world.chunk_ticking.PlayerChunkWatchingManagerMixin' as rule 'mixin.world.chunk_ticking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.821] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'world.chunk_ticking.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.chunk_ticking' (added by user configuration) disables it and children
[18Dec2021 20:58:08.827] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by user configuration) disables it and children
[18Dec2021 20:58:08.828] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'world.tick_scheduler.ServerWorldMixin' as rule 'mixin.world.tick_scheduler' (added by user configuration) disables it and children
[18Dec2021 20:58:09.893] [main/WARN] [mixin/]: @Final field field_243599_b:Ljava/util/Map; in biomeidfixer.mixins.json:MixinDynamicRegistries should be final
[18Dec2021 20:58:09.894] [main/WARN] [mixin/]: @Final field field_243600_c:Lnet/minecraft/util/registry/DynamicRegistries$Impl; in biomeidfixer.mixins.json:MixinDynamicRegistries should be final
[18Dec2021 20:58:10.674] [main/INFO] [net.minecraftforge.coremod.CoreMod.somnia/COREMODLOG]: Patching class ServerPlayerEntity
[18Dec2021 20:58:10.892] [main/WARN] [mixin/]: Injection warning: LVT in net/minecraft/entity/player/PlayerEntity::func_71059_n(Lnet/minecraft/entity/Entity;)V has incompatible changes at opcode 373 in callback mining-master.mixins.json:MixinPlayerEntity->@Inject::MM_calculateLeechingHeal(Lnet/minecraft/entity/Entity;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;FFFZZFZLnet/minecraftforge/event/entity/player/CriticalHitEvent;ZDFZILnet/minecraft/util/math/vector/Vector3d;Z)V.
 Expected: [F, F, F, Z, Z, F, Z, Lnet/minecraftforge/event/entity/player/CriticalHitEvent;, Z, D, F, Z, I, Lnet/minecraft/util/math/vector/Vector3d;, Z]
    Found: [F, F, F, Z, Z, I, Z, Lnet/minecraftforge/event/entity/player/CriticalHitEvent;, Z, D, F, Z, I, Lnet/minecraft/util/math/vector/Vector3d;, Z]
Available: [F, F, F, Z, Z, I, Z, Lnet/minecraftforge/event/entity/player/CriticalHitEvent;, Z, D, F, Z, I, Lnet/minecraft/util/math/vector/Vector3d;, Z]
[18Dec2021 20:58:10.892] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:66)
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:63)
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:60)
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18Dec2021 20:58:10.893] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 7 more
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[18Dec2021 20:58:10.894] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.server.MinecraftServer.<clinit>(MinecraftServer.java:187)
[18Dec2021 20:58:10.895] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.server.Main.main(Main.java:108)
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 13 more
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method MM_calculateLeechingHeal(Lnet/minecraft/entity/Entity;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;FFFZZFZLnet/minecraftforge/event/entity/player/CriticalHitEvent;ZDFZILnet/minecraft/util/math/vector/Vector3d;Z)V in mining-master.mixins.json:MixinPlayerEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mining-master.refmap.json
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[18Dec2021 20:58:10.896] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	... 30 more
```

**Comment by Cixon** [comment]
bump!
