### ISSUE TITLE
[Bug]:  Magma-1.16.5-36.2.19-5a1cac0-STABLE - DW20 1.16 Version 1.12.0 - Mobs/Animals not giving loot when killed

### ISSUE THREAD

**Issue by alicheek** [magmafoundation/Magma-1.16.x#208]
### What happened?

When killing mobs/animals you do not get any form of loot.

For example Killing cow with  stone sword will not give you the meat at any point

I have put below the log but not sure if this is related to the issue above.

### Mods

DW20 1.16

### Mod Version

1.12.0

### Magma Version

1.16.5-36.2.19-5a1cac0-STABLE

### OS

Linux

### Relevant log output

```shell
[Minecraft/]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.entity.MobEntity.setAttackTarget(MobEntity.java:228) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70624_b(MobEntity.java:216) ~[?:?]
	at com.ma.entities.ai.RetaliateOnAttackGoal.func_75249_e(RetaliateOnAttackGoal.java:67) ~[mana-and-artifice:1.5.0.10]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_220877_a(SourceFile:83) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:77) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:758) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2827) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:552) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2571) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:348) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:732) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:742) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:505) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1118) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:381) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1032) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:869) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by alicheek** [comment]
Another error that is coming up on logs:

[Minecraft/]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.entity.MobEntity.setAttackTarget(MobEntity.java:228) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70624_b(MobEntity.java:216) ~[?:?]
	at com.ma.entities.ai.RetaliateOnAttackGoal.func_75249_e(RetaliateOnAttackGoal.java:67) ~[mana-and-artifice:1.5.0.10]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_220877_a(SourceFile:83) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:77) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:758) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2827) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:552) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2571) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:348) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:732) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:742) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:505) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1118) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:381) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1032) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:869) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by UeberallGebannt** [comment]
Fixed in latest dev
