### ISSUE TITLE
[Bug]: Server won't launch on brand new installation

### ISSUE THREAD

**Issue by ffpp2003** [magmafoundation/Magma-1.16.x#210]
### What happened?

I can't launch magma on a brand new installation. I followed the installation instructions written on the README.md file

Since I cant paste the installation output log where is ment to be, I upload it:
[Magma-1.16.5-36.2.19-5a1cac0-STABLE-installer.jar.log](https://github.com/magmafoundation/Magma-1.16.x/files/7811692/Magma-1.16.5-36.2.19-5a1cac0-STABLE-installer.jar.log)
 

### Mods

None, its a brand new server

### Mod Version

None, its a brand new server

### Magma Version

Magma-1.16.5-36.2.19-5a1cac0-STABLE

### OS

Windows

### Relevant log output

```shell
D:\Users\ffpp2\AppData\Roaming\.minecraft\Servers\Magma\1.16.5-36.2.19-5a1cac0-STABLE>java -jar forge-1.16.5-36.2.19-5a1cac0-STABLE.jar
[23:31:41] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.19-5a1cac0-STABLE, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[23:31:41] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 17.0.1 by Oracle Corporation
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x70beb599) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x70beb599
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:67)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:64)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:61)
```

**Comment by UeberallGebannt** [comment]
Use Java 8-11 (8 recommended)
