### ISSUE TITLE
[Bug]: InvokeSpecial constructor missing/removed, causing incompat with several mods

### ISSUE THREAD

**Issue by Colin-J-Wood** [magmafoundation/Magma-1.16.x#213]
### What happened?

An important constructor has gone missing in magma that makes a lot of important mods to my pack incompatible with it.

### Mods

Kaleidio's Battle Pack Server 4.2.2, see below for curseforge install

### Mod Version

log contains information

### Magma Version

DEV - 36.2.23-a18dc70

### OS

Windows

### Relevant log output

```shell
///example of constructor for a mod trying to use invoke special:
...<init>(EntityType,World)void/newInvokeSpecial

///list of mods that failed:
        Suspected Mods: None[06:37:46] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        MrCrayfish's Gun Mod (cgm) has failed to load correctly
§7org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered,
        Atum 2 (atum) has failed to load correctly
§7java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.entity.projectile.ProjectileEntity,
        More Red (morered) has failed to load correctly
§7org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered,
        MrCrayfish's Vehicle Mod (vehicle) has failed to load correctly
§7java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.mrcrayfish.vehicle.entity.vehicle.ATVEntity.<init>(EntityType,World)void/newInvokeSpecial,
        Architectury (architectury) has failed to load correctly
§7java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.entity.Entity,
        Not Enough Noteblock (noteblockne) has failed to load correctly
§7java.lang.NoClassDefFoundError: net.minecraft.entity.Entity,
        Create (create) has failed to load correctly
§7java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.simibubi.create.content.contraptions.components.structureMovement.OrientedContraptionEntity.<init>(EntityType,World)void/newInvokeSpecial,
        Quark (quark) has failed to load correctly
§7java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: vazkii.quark.content.tools.entity.PickarangEntity.<init>(EntityType,World)void/newInvokeSpecial,
        Create Crafts & Additions (createaddition) has failed to load correctly
§7java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.mrh0.createaddition.entities.overcharged_hammer.OverchargedHammerEntity.<init>(EntityType,World)void/newInvokeSpecial
]

///full log:
https://pastebin.com/N1XtJqUc
```

**Comment by Colin-J-Wood** [comment]
here's a more full example of this:
Caused by 1: java.lang.IllegalAccessError: no such constructor: com.mrh0.createaddition.entities.overcharged_hammer.OverchargedHammerEntity.<init>(EntityType,World)void/newInvokeSpecial
                at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483) ~[?:1.8.0_312] {}
                at com.mrh0.createaddition.index.CAEntities.<clinit>(CAEntities.java:18) ~[createaddition:1.16.5-20220129a] {re:classloading}
                at com.mrh0.createaddition.CreateAddition.<init>(CreateAddition.java:103) ~[createaddition:1.16.5-20220129a] {re:classloading}
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_312] {}
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_312] {}
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_312] {}
