### ISSUE TITLE
[BUG] Exception in Byte

### ISSUE THREAD

**Issue by TheRealM18** [magmafoundation/Magma-1.16.x#36]
I'm not sure what this bug is, but I know how to reproduce it.

It is something with the structurizer's custom command, and how it works.  It is fine in Forge, but does not like Magma for some reason.

`[19:51:27] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
        Index: 6
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$2695/1037367581@4610c1ac
                2: ASM: class vazkii.patchouli.common.handler.PlayerJoinHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                3: ASM: class com.ldtteam.structurize.event.EventSubscriber onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                4: ASM: net.minecraftforge.common.ForgeInternalHandler@5aa82bb7 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                5: ASM: class com.minecolonies.coremod.event.EventHandler onPlayerEnterWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                6: ASM: class com.minecolonies.coremod.event.FMLEventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                7: ASM: class com.minecolonies.coremod.util.FurnaceRecipes onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                8: ASM: squeek.appleskin.network.SyncHandler@13414444 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.NullPointerException
        at com.minecolonies.api.network.PacketUtils.writeUUID(PacketUtils.java:32)
        at com.minecolonies.coremod.network.messages.client.ServerUUIDMessage.toBytes(ServerUUIDMessage.java:38)
        at com.minecolonies.coremod.network.NetworkChannel.handleSplitting(NetworkChannel.java:416)
        at com.minecolonies.coremod.network.NetworkChannel.sendToPlayer(NetworkChannel.java:298)
        at com.minecolonies.coremod.event.FMLEventHandler.onPlayerLogin(FMLEventHandler.java:45)
        at net.minecraftforge.eventbus.ASMEventHandler_79_FMLEventHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:326)
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:169)
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:71)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:234)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:141)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1200)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:368)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1081)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:914)
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:277)
        at java.lang.Thread.run(Unknown Source)

[19:51:27] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /127.0.0.1:59125
java.lang.NullPointerException: null
        at com.minecolonies.api.network.PacketUtils.writeUUID(PacketUtils.java:32) ~[?:0.13.401-BETA] {re:classloading}
        at com.minecolonies.coremod.network.messages.client.ServerUUIDMessage.toBytes(ServerUUIDMessage.java:38) ~[?:0.13.401-BETA] {re:classloading}
        at com.minecolonies.coremod.network.NetworkChannel.handleSplitting(NetworkChannel.java:416) ~[?:0.13.401-BETA] {re:classloading}
        at com.minecolonies.coremod.network.NetworkChannel.sendToPlayer(NetworkChannel.java:298) ~[?:0.13.401-BETA] {re:classloading}
        at com.minecolonies.coremod.event.FMLEventHandler.onPlayerLogin(FMLEventHandler.java:45) ~[?:0.13.401-BETA] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_79_FMLEventHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[?:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:326) ~[?:?] {re:classloading,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimapfair:xaero_playerlist_sendworldinfo,pl:runtimedistcleaner:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:169) ~[?:?] {re:classloading}
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:71) ~[?:?] {re:classloading}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:234) ~[?:?] {re:classloading,xf:fml:lightoverlay-forge:light-overlay-forge,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:141) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1200) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:368) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1081) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:914) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:277) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}
[19:51:27] [Netty Server IO magmafoundation/Magma-1.16.x#20/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@6265effa (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[19:51:27] [Netty Server IO magmafoundation/Magma-1.16.x#20/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@3beeb1e3 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[19:51:27] [Netty Server IO magmafoundation/Magma-1.16.x#20/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.ldtteam.structurize.commands.arguments.MultipleStringArgument@73b8c260 (class com.ldtteam.structurize.commands.arguments.MultipleStringArgument) - will not be sent to client!`

not sure why Magma will not except it, but it won't.  If you want to contact Minecolonies team as well, there is other times this but has come into play and making other launchers upset.

**Comment by Hexeption** [comment]
Fixed
