### ISSUE TITLE
Worldedit not work

### ISSUE THREAD

**Issue by chrishdx** [magmafoundation/Magma-1.16.x#83]
Hello,

Worldedit does not work with the current build. It is always started with an error but not activated. 

This ist with 7.3 Worldedit

[11:14:36] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling WorldEdit v7.3.0-SNAPSHOT+5647-476342a (Is it up to date?)
java.lang.NullPointerException: null
        at com.sk89q.wepif.PermissionsResolverManager.loadConfig(PermissionsResolverManager.java:227) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.sk89q.wepif.PermissionsResolverManager.<init>(PermissionsResolverManager.java:103) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.sk89q.wepif.PermissionsResolverManager.initialize(PermissionsResolverManager.java:66) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:152) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:494) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:408) ~[forge:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:237) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:761) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:280) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

and with 7.2

[11:16:48] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling WorldEdit v7.2.2+fc3c499 (Is it up to date?)
java.lang.NullPointerException: null
        at com.sk89q.wepif.PermissionsResolverManager.loadConfig(PermissionsResolverManager.java:227) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.sk89q.wepif.PermissionsResolverManager.<init>(PermissionsResolverManager.java:103) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.sk89q.wepif.PermissionsResolverManager.initialize(PermissionsResolverManager.java:66) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:152) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:494) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:408) ~[forge:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:237) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:761) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:280) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

**Comment by superJK92iscool** [comment]
Try using Fast Async World Edit instead of World Edit because it is better and a lot of servers use it

**Comment by chrishdx** [comment]
> Try using Fast Async World Edit instead of World Edit because it is better and a lot of servers use it. If i start the first Time the FAWE Plugin it works i can use the we commands but if i restart it it does not work.

thanks for your answer but its the same 

[21:08:22] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling FastAsyncWorldEdit v1.16-596;eead11f (Is it up to date?)
java.lang.NullPointerException: null
        at com.sk89q.wepif.PermissionsResolverManager.loadConfig(PermissionsResolverManager.java:227) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.sk89q.wepif.PermissionsResolverManager.<init>(PermissionsResolverManager.java:103) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.sk89q.wepif.PermissionsResolverManager.initialize(PermissionsResolverManager.java:66) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:144) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:494) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:408) ~[forge:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:237) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:761) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:280) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

**Comment by superJK92iscool** [comment]
Odd what version of minecraft are you using (i.e. 1.16.5, 1.16.3, etc)

**Comment by chrishdx** [comment]
1.16.5 i was build this Magma Server nur i change the Magma repo because they are Not working

**Comment by superJK92iscool** [comment]
Try this https://www.curseforge.com/minecraft/mc-mods/worldedit/files/3172951 (put it in the mods folder

**Comment by superJK92iscool** [comment]
Also remove the plugin one

**Comment by superJK92iscool** [comment]
Did that fix it

**Comment by chrishdx** [comment]
hello sorry that I only get in touch now, but I came this morning to test it yes with the mod it works but then i can't use worldguard i just switched to mohist because the 1.16.5 version runs better there i could also use worldguard nevertheless a thousand thanks for the effort

**Comment by superJK92iscool** [comment]
No problem

**Comment by superJK92iscool** [comment]
Also don't forget to close this issue
